[2022-07-23 14:27:07,592] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: local_to_snowflake.load_to_snowflake manual__2022-07-23T14:26:36.128276+00:00 [queued]>
[2022-07-23 14:27:07,607] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: local_to_snowflake.load_to_snowflake manual__2022-07-23T14:26:36.128276+00:00 [queued]>
[2022-07-23 14:27:07,607] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-23 14:27:07,607] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-07-23 14:27:07,607] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-23 14:27:07,636] {taskinstance.py:1397} INFO - Executing <Task(S3ToSnowflakeOperator): load_to_snowflake> on 2022-07-23 14:26:36.128276+00:00
[2022-07-23 14:27:07,646] {standard_task_runner.py:52} INFO - Started process 13714 to run task
[2022-07-23 14:27:07,653] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'local_to_snowflake', 'load_to_snowflake', 'manual__2022-07-23T14:26:36.128276+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/localtosnowflake.py', '--cfg-path', '/tmp/tmpscorebj4', '--error-file', '/tmp/tmpbcu8tf74']
[2022-07-23 14:27:07,655] {standard_task_runner.py:80} INFO - Job 67: Subtask load_to_snowflake
[2022-07-23 14:27:07,777] {task_command.py:371} INFO - Running <TaskInstance: local_to_snowflake.load_to_snowflake manual__2022-07-23T14:26:36.128276+00:00 [running]> on host cbd64c50b1d6
[2022-07-23 14:27:07,934] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=local_to_snowflake
AIRFLOW_CTX_TASK_ID=load_to_snowflake
AIRFLOW_CTX_EXECUTION_DATE=2022-07-23T14:26:36.128276+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-23T14:26:36.128276+00:00
[2022-07-23 14:27:07,936] {s3_to_snowflake.py:128} INFO - Executing COPY command...
[2022-07-23 14:27:07,960] {base.py:68} INFO - Using connection ID 'my_snowflake_conn' for task execution.
[2022-07-23 14:27:07,984] {connection.py:262} INFO - Snowflake Connector for Python Version: 2.7.9, Python Version: 3.7.13, Platform: Linux-5.15.0-1014-azure-x86_64-with-debian-11.4
[2022-07-23 14:27:07,985] {connection.py:877} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2022-07-23 14:27:07,985] {connection.py:894} INFO - Setting use_openssl_only mode to False
[2022-07-23 14:27:09,749] {cursor.py:710} INFO - query: [ALTER SESSION SET autocommit=True]
[2022-07-23 14:27:10,021] {cursor.py:734} INFO - query execution done
[2022-07-23 14:27:10,022] {snowflake.py:328} INFO - Running statement: COPY INTO YELLOW_TRIPDATA
FROM @YELLOW_TRIPDATA_STAGE/
file_format=(type = 'CSV', skip_header = 1, time_format = 'YYYY-MM-DD HH24:MI:SS'), parameters: None
[2022-07-23 14:27:10,022] {cursor.py:710} INFO - query: [COPY INTO YELLOW_TRIPDATA FROM @YELLOW_TRIPDATA_STAGE/ file_format=(type = 'CSV'...]
[2022-07-23 14:30:47,791] {cursor.py:734} INFO - query execution done
[2022-07-23 14:30:47,792] {snowflake.py:338} INFO - Statement execution info - {'file': 's3://snowflakedata212/yellow_tripdata_sample_2019-01.csv', 'status': 'LOADED', 'rows_parsed': 10000, 'rows_loaded': 10000, 'error_limit': 1, 'errors_seen': 0, 'first_error': None, 'first_error_line': None, 'first_error_character': None, 'first_error_column_name': None}
[2022-07-23 14:30:47,792] {snowflake.py:338} INFO - Statement execution info - {'file': 's3://snowflakedata212/yellow_tripdata_sample_2019-02.csv', 'status': 'LOADED', 'rows_parsed': 10000, 'rows_loaded': 10000, 'error_limit': 1, 'errors_seen': 0, 'first_error': None, 'first_error_line': None, 'first_error_character': None, 'first_error_column_name': None}
[2022-07-23 14:30:47,792] {snowflake.py:342} INFO - Rows affected: 2
[2022-07-23 14:30:47,793] {snowflake.py:343} INFO - Snowflake query id: 01a5cce3-0000-da87-0000-225900051622
[2022-07-23 14:30:47,793] {connection.py:507} INFO - closed
[2022-07-23 14:30:48,046] {connection.py:510} INFO - No async queries seem to be running, deleting session
[2022-07-23 14:30:48,318] {s3_to_snowflake.py:130} INFO - COPY command completed
[2022-07-23 14:30:48,377] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=local_to_snowflake, task_id=load_to_snowflake, execution_date=20220723T142636, start_date=20220723T142707, end_date=20220723T143048
[2022-07-23 14:30:48,422] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-23 14:30:48,487] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
