[2022-07-27 18:46:23,681] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dataquality_pipeline_v3.check_row_count manual__2022-07-27T18:45:32.236182+00:00 [queued]>
[2022-07-27 18:46:23,750] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dataquality_pipeline_v3.check_row_count manual__2022-07-27T18:45:32.236182+00:00 [queued]>
[2022-07-27 18:46:23,750] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-27 18:46:23,750] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-07-27 18:46:23,750] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-27 18:46:23,838] {taskinstance.py:1397} INFO - Executing <Task(SnowflakeValueCheckOperator): check_row_count> on 2022-07-27 18:45:32.236182+00:00
[2022-07-27 18:46:23,887] {standard_task_runner.py:52} INFO - Started process 8003 to run task
[2022-07-27 18:46:23,910] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dataquality_pipeline_v3', 'check_row_count', 'manual__2022-07-27T18:45:32.236182+00:00', '--job-id', '156', '--raw', '--subdir', 'DAGS_FOLDER/dataquality_pipeline_v3.py', '--cfg-path', '/tmp/tmp21h2x37d', '--error-file', '/tmp/tmpf68yaiut']
[2022-07-27 18:46:23,928] {standard_task_runner.py:80} INFO - Job 156: Subtask check_row_count
[2022-07-27 18:46:24,524] {task_command.py:371} INFO - Running <TaskInstance: dataquality_pipeline_v3.check_row_count manual__2022-07-27T18:45:32.236182+00:00 [running]> on host 2c2de32fb47f
[2022-07-27 18:46:25,202] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=abin404@yopmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dataquality_pipeline_v3
AIRFLOW_CTX_TASK_ID=check_row_count
AIRFLOW_CTX_EXECUTION_DATE=2022-07-27T18:45:32.236182+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-27T18:45:32.236182+00:00
[2022-07-27 18:46:25,203] {sql.py:204} INFO - Executing SQL check: SELECT COUNT(*) FROM YELLOW_TRIPDATA;
[2022-07-27 18:46:25,266] {base.py:68} INFO - Using connection ID 'snowflake_default' for task execution.
[2022-07-27 18:46:25,293] {connection.py:262} INFO - Snowflake Connector for Python Version: 2.7.9, Python Version: 3.7.13, Platform: Linux-5.15.0-1014-azure-x86_64-with-debian-11.4
[2022-07-27 18:46:25,294] {connection.py:877} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2022-07-27 18:46:25,294] {connection.py:894} INFO - Setting use_openssl_only mode to False
[2022-07-27 18:46:29,043] {cursor.py:710} INFO - query: [SELECT COUNT(*) FROM YELLOW_TRIPDATA;]
[2022-07-27 18:46:29,438] {cursor.py:734} INFO - query execution done
[2022-07-27 18:46:29,439] {connection.py:507} INFO - closed
[2022-07-27 18:46:29,684] {connection.py:510} INFO - No async queries seem to be running, deleting session
[2022-07-27 18:46:30,300] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=dataquality_pipeline_v3, task_id=check_row_count, execution_date=20220727T184532, start_date=20220727T184623, end_date=20220727T184630
[2022-07-27 18:46:30,839] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-27 18:46:31,353] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
